Add Document update and create APIs
DSD-DBS/polarion-rest-api-client pull request #40
Opened 2024-07-04 06:31 UTC by micha91

With this PR we add the high level APIs for document creation and updating documents. In addition, we introduce the Rendering Layouts to the Document class to enable control over WorkItem representations.

2024-07-12 16:03 UTC, ewuerger requested changes
Only one to resolve (`module_folder` for every document in the list). The others are pain points which could be addressed sometime else.

Then: LGTM.

2024-07-12 16:44 UTC, micha91 commented on polarion_rest_api_client/clients/documents.py
> +        assert items[0].module_folder is not None, "module folder must be set"
Nope, `_create` is called by from the `create` method of the super class. Before `_create` is called, all documents are grouped by their `module_folder` using the `_split_into_batches` method (see line 105+). For that reason all `module_folders` of `items` should have the same folder

2024-07-15 10:13 UTC, micha91 commented on tests/conftest.py
> +def fixture_new_client():
see #41

2024-07-15 10:14 UTC, micha91 commented on polarion_rest_api_client/clients/documents.py
> +            client=self._client.client,
see #42

2024-07-15 10:14 UTC, micha91 commented on polarion_rest_api_client/clients/documents.py
> +        assert items[0].module_folder is not None, "module folder must be set"
a comment was added

2024-07-15 10:35 UTC, ewuerger approved these changes
LGTM

2024-07-15 10:37 UTC, merged